/**
 * The label layer, and the scope channel over it.
 *
 * ADR 0003's two axes are orthogonal because a single exclusive enum
 * misclassifies every interesting file in the fixtures, and always in the same
 * direction — it drops real source out of the graph. These pin that, the
 * precedence between signals, and the one rule the scope channel exists to
 * obey: an exclusion is a count, never a blind spot.
 */

import { execFileSync } from 'node:child_process'
import { cpSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import { parseConfig, DEFAULT_CONFIG } from '../src/config/index.ts'
import {
  effective,
  labelFiles,
  parseFilter,
  scopeOf,
  UNSCOPED,
} from '../src/labels/index.ts'
import { classification } from '../src/operations/classification.ts'
import { symbol } from '../src/operations/symbol.ts'
import { callers } from '../src/operations/calls.ts'
import { openSession } from '../src/session/index.ts'
import { walkSourceFiles } from '../src/drift.ts'

/**
 * codedocs' own `packages/`, which is the largest tree a test can rely on.
 *
 * Not the repository root: `repos/` holds the cloned fixtures the ADRs were
 * measured on, so a walk from there measures whatever a developer has checked
 * out rather than anything repeatable.
 */
const packages = join(dirname(fileURLToPath(import.meta.url)), '..', '..')

const fixture = join(
  dirname(fileURLToPath(import.meta.url)),
  'fixtures',
  'basic',
)
let root: string

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), 'codedocs-labels-'))
  cpSync(fixture, root, { recursive: true })
  writeFileSync(
    join(root, 'package.json'),
    '{"name":"fixture","private":true}\n',
  )
  mkdirSync(join(root, 'node_modules'), { recursive: true })
})

afterEach(() => {
  rmSync(root, { recursive: true, force: true })
})

/** Put a file on disk, making its directory first. */
function write(path: string, content = 'export const x = 1\n'): void {
  mkdirSync(join(root, dirname(path)), { recursive: true })
  writeFileSync(join(root, path), content)
}

/** Make the fixture a git repository, and track everything currently in it. */
function commit(): void {
  const git = (...args: string[]): void => {
    execFileSync('git', args, { cwd: root, stdio: 'ignore' })
  }
  git('init', '-q')
  git('config', 'user.email', 'fixture@example.com')
  git('config', 'user.name', 'Fixture')
  git('add', '-A')
  git('commit', '-qm', 'fixture')
}

/** The labels one file carries, as the pass produced them. */
const labelsOf = (path: string, config = DEFAULT_CONFIG) =>
  labelFiles(root, [path], config).labels.map(
    ({ axis, value, provenance, derivation }) => ({
      axis,
      value,
      provenance,
      derivation,
    }),
  )

/** What one file is, once precedence has decided. */
const decide = (path: string, config = DEFAULT_CONFIG) =>
  effective(labelFiles(root, [path], config).labels).get(path)

describe('the two axes', () => {
  it('are orthogonal: a config file is still authored', () => {
    write('vitest.config.ts')
    expect(decide('vitest.config.ts')).toMatchObject({
      role: 'config',
      authorship: 'authored',
    })
  })

  it('are orthogonal the other way: generated code is still source', () => {
    write('src/api.generated.ts')
    expect(decide('src/api.generated.ts')).toMatchObject({
      role: 'source',
      authorship: 'generated',
    })
  })

  it('default to `source` and `authored`, stored rather than assumed', () => {
    write('src/plain.ts')
    expect(labelsOf('src/plain.ts')).toEqual([
      {
        axis: 'role',
        value: 'source',
        provenance: 'inferred',
        derivation: 'default',
      },
      {
        axis: 'authorship',
        value: 'authored',
        provenance: 'inferred',
        derivation: 'default',
      },
    ])
  })

  it('call a test helper a test, because everything excluding tests means it to', () => {
    write('src/__mocks__/stripe.ts')
    expect(decide('src/__mocks__/stripe.ts')?.role).toBe('test')
  })
})

describe('the signals, and what each one is worth', () => {
  it('reads git for authorship, which is the deterministic half', () => {
    write('src/tracked.ts')
    commit()
    write('src/untracked.ts')

    expect(labelsOf('src/tracked.ts')).toContainEqual({
      axis: 'authorship',
      value: 'authored',
      provenance: 'deterministic',
      derivation: 'git-untracked',
    })
    expect(decide('src/untracked.ts')?.authorship).toBe('generated')
  })

  it('reads a generated header, and only in the first five lines', () => {
    write('src/header.ts', '/** @generated by a tool */\nexport const a = 1\n')
    write(
      'src/later.ts',
      ['1', '2', '3', '4', '5', '// @generated', ''].join('\n'),
    )

    expect(decide('src/header.ts')?.authorship).toBe('generated')
    expect(decide('src/later.ts')?.authorship).toBe('authored')
  })

  it('says a path convention is inferred, because a name proves nothing', () => {
    write('src/thing.test.ts')
    expect(labelsOf('src/thing.test.ts')).toContainEqual({
      axis: 'role',
      value: 'test',
      provenance: 'inferred',
      derivation: 'path-convention',
    })
  })

  it('keeps every signal that fired, not only the one that won', () => {
    // The union is what lets an answer name the rule that classified a file,
    // and what lets `doctor` report where two rules disagreed.
    write('src/api.generated.ts', '/** @generated */\nexport const a = 1\n')
    const derivations = labelsOf('src/api.generated.ts')
      .filter((label) => label.axis === 'authorship')
      .map((label) => label.derivation)

    expect(derivations).toEqual(['default', 'generated-header', 'codegen-path'])
  })
})

describe('codedocs.jsonc `classify`', () => {
  const config = (text: string) => parseConfig(text)

  it('overrides every other signal, at the highest precedence', () => {
    write('src/thing.test.ts')
    const rules = config(
      '{"classify": {"src/thing.test.ts": {"role": "source"}}}',
    )
    expect(decide('src/thing.test.ts', rules)?.role).toBe('source')
  })

  it('takes the last matching rule, so a narrow one goes below a broad one', () => {
    write('src/generated/thing.ts')
    const rules = config(
      '{"classify": {' +
        '"src/**": {"authorship": "authored"},' +
        '"src/generated/**": {"authorship": "generated"}' +
        '}}',
    )
    expect(decide('src/generated/thing.ts', rules)?.authorship).toBe(
      'generated',
    )
  })

  it('is a label like any other, so an answer can name the line that caused it', () => {
    write('src/plain.ts')
    const rules = config('{"classify": {"src/*.ts": {"role": "config"}}}')
    expect(labelsOf('src/plain.ts', rules)).toContainEqual({
      axis: 'role',
      value: 'config',
      provenance: 'deterministic',
      derivation: 'user-config',
    })
  })

  it('reads the whole glob vocabulary, and a literal that is not one', () => {
    write('src/deep/thing.ts')
    write('src/a.ts')
    write('src/plus+one.ts')

    // `**` crosses separators, `*` stops at one, `?` is a single character, and
    // a regex metacharacter in a path is a literal.
    expect(
      decide(
        'src/deep/thing.ts',
        config('{"classify": {"src/**": {"role": "config"}}}'),
      )?.role,
    ).toBe('config')
    expect(
      decide(
        'src/deep/thing.ts',
        config('{"classify": {"src/*.ts": {"role": "config"}}}'),
      )?.role,
    ).not.toBe('config')
    expect(
      decide(
        'src/a.ts',
        config('{"classify": {"src/?.ts": {"role": "config"}}}'),
      )?.role,
    ).toBe('config')
    expect(
      decide(
        'src/plus+one.ts',
        config('{"classify": {"src/plus+one.ts": {"role": "config"}}}'),
      )?.role,
    ).toBe('config')
  })

  it('leaves a file no rule matches to the signals entirely', () => {
    write('src/plain.ts')
    const rules = config('{"classify": {"other/**": {"role": "config"}}}')
    expect(labelsOf('src/plain.ts', rules)).not.toContainEqual(
      expect.objectContaining({ derivation: 'user-config' }),
    )
  })

  it('may set one axis and leave the other to the signals', () => {
    write('src/thing.test.ts')
    const rules = config(
      '{"classify": {"src/**": {"authorship": "generated"}}}',
    )
    expect(decide('src/thing.test.ts', rules)).toMatchObject({
      role: 'test',
      authorship: 'generated',
    })
  })
})

describe('the label filter', () => {
  it('refuses a value it does not know, rather than matching nothing', () => {
    expect(parseFilter('role=source')).toEqual({
      filter: { axis: 'role', value: 'source' },
    })
    expect(parseFilter('role=nope')).toHaveProperty('expected')
    expect(parseFilter('nope=source')).toHaveProperty('expected')
  })

  it('replaces the default on the axis it names, and no other', () => {
    const scope = scopeOf([{ axis: 'role', value: 'test' }], [])
    expect(scope.include).toEqual([
      { axis: 'authorship', value: 'authored' },
      { axis: 'role', value: 'test' },
    ])

    const asked = scopeOf([{ axis: 'authorship', value: 'generated' }], [])
    expect(asked.include).toEqual([{ axis: 'authorship', value: 'generated' }])
  })
})

describe('the scope channel, over a real index', () => {
  /** Open a session, ask, and close it. */
  function ask<T>(read: (open: ReturnType<typeof openSession>) => T): T {
    const open = openSession({ cwd: root, noUpdate: false })
    try {
      return read(open)
    } finally {
      open.close()
    }
  }

  it('excludes by label and says how many, never as a blind spot', () => {
    write(
      'src/extra.test.ts',
      "import { charge } from './payments.ts'\n" +
        'export const runs = (): string => charge(1)\n',
    )

    const scoped = ask((open) =>
      symbol(open.store, open.context, ['*'], null, {
        scope: scopeOf([], [{ axis: 'role', value: 'test' }]),
        labels: open.labels(),
      }),
    )
    const entry = scoped.result?.[0]

    expect(entry?.excluded).toBeGreaterThan(0)
    // The one rule the channel exists to obey: codedocs knows exactly what it
    // withheld, so it is a count rather than something it could not see.
    expect(entry?.blindSpots).toEqual([])
    expect(
      (entry?.result ?? []).some((node) => node.file.includes('.test.')),
    ).toBe(false)
  })

  it('echoes the scope on every answer, including when nothing was excluded', () => {
    const envelope = ask((open) =>
      callers(open.store, open.context, ['charge'], null, {
        scope: scopeOf([], []),
        labels: open.labels(),
      }),
    )
    expect(envelope.request.scope.include).toEqual([
      { axis: 'authorship', value: 'authored' },
    ])
    expect(envelope.result?.[0]?.excluded).toBe(0)
  })

  it('leaves test callers in by default, so tested code never reads as dead', () => {
    // The Redwood Cells trap the backend spike found: hiding test callers makes
    // tested-but-unreferenced code look unused.
    write(
      'src/charge.test.ts',
      "import { charge } from './payments.ts'\nexport const run = (): string => charge(1)\n",
    )

    const envelope = ask((open) =>
      callers(open.store, open.context, ['charge'], null, {
        scope: scopeOf([], []),
        labels: open.labels(),
      }),
    )
    expect(
      (envelope.result?.[0]?.result ?? []).some((edge) =>
        edge.file.includes('.test.'),
      ),
    ).toBe(true)
  })

  it('filters nothing when it is given nothing to filter with', () => {
    const envelope = ask((open) =>
      symbol(open.store, open.context, ['*'], null, UNSCOPED),
    )
    expect(envelope.result?.[0]?.excluded).toBe(0)
  })
})

describe('the classification report', () => {
  it('counts each pair with the signals that decided it', () => {
    write('src/thing.test.ts')
    const pass = labelFiles(
      root,
      ['src/plain.ts', 'src/thing.test.ts'],
      DEFAULT_CONFIG,
    )
    const found = classification(pass.labels)

    expect(found.counts).toEqual([
      {
        role: 'source',
        authorship: 'authored',
        files: 1,
        derivations: ['default'],
      },
      {
        role: 'test',
        authorship: 'authored',
        files: 1,
        derivations: ['default', 'path-convention'],
      },
    ])
  })

  it('names a file whose classification is a guess rather than evidence', () => {
    const pass = labelFiles(root, ['src/thing.test.ts'], DEFAULT_CONFIG)
    expect(classification(pass.labels).inferred).toEqual(['src/thing.test.ts'])
  })

  it('names the file where two signals disagree, which is where config is owed', () => {
    // The case ADR 0003 names: an `@generated` header without the matching name.
    write('src/mixed.ts', '// @generated\nexport const a = 1\n')
    const rules = parseConfig(
      '{"classify": {"src/mixed.ts": {"authorship": "authored"}}}',
    )
    const found = classification(
      labelFiles(root, ['src/mixed.ts'], rules).labels,
    )

    expect(found.disagreements).toHaveLength(1)
    expect(
      found.disagreements[0]?.values.map((held) => held.derivation),
    ).toEqual(['generated-header', 'user-config'])
  })
})

describe('what the pass costs', () => {
  it('measures itself, so the assumption that justified it stays checkable', async ({
    annotate,
  }) => {
    // Over the repository this test runs in rather than a two-file fixture: the
    // measurement that justified recomputing the whole layer — ~0.9 s over
    // cal.com's 5,025 files — is only checkable against a real tree.
    const files = walkSourceFiles(packages)
    const pass = labelFiles(packages, files, DEFAULT_CONFIG)

    // `codedocs analyse` prints this line on every run that relabels, which is
    // where a reader actually meets the number; the annotation is for whoever
    // is reading the test.
    await annotate(
      `label pass: ${pass.files} files in ${pass.durationMs} ms ` +
        `(${pass.labels.length} labels, git ${pass.tracked ? 'answered' : 'absent'})`,
    )

    expect(pass.files).toBe(files.length)
    expect(pass.labels.length).toBeGreaterThan(files.length)
    // ADR 0003 skipped incremental invalidation on the strength of ~0.9 s over
    // 5,025 files. A tree this size has to be far inside that, or the trade is
    // no longer the one that was made.
    expect(pass.durationMs).toBeLessThan(2000)
  })
})
