/**
 * Writes `bench/RESULTS.md` from the records on disk.
 *
 *   node bench/writeup.ts            rewrite RESULTS.md
 *   node bench/writeup.ts --stdout   print it instead
 *
 * The write-up is the thing the benchmark exists to produce, and it is
 * generated rather than written so that it cannot drift from the runs. Every
 * number in it comes from `bench/results/`; the prose around them states what
 * the set does and does not support, computed from the same records.
 *
 * The two questions are reported in separate blocks. A like-for-like block
 * varies only the toolset. A cross-model block varies the model too, which is
 * where the "can a cheaper model with structural facts do the dearer one's
 * work" question lives. Pooling them would answer neither.
 */

import { writeFileSync } from 'node:fs'
import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { armsIn, readRecord } from './arms.ts'
import { has } from './argv.ts'
import { casesById } from './cases.ts'
import {
  type Comparison,
  comparisonsIn,
  questionOf,
  runsOf,
} from './comparisons.ts'
import { heading, sections } from './markdown.ts'
import { BENCH, RESULTS } from './paths.ts'
import {
  colophon,
  type Coverage,
  howToRead,
  limits,
  provenance,
  question,
  standing,
} from './writeup-prose.ts'
import {
  discardedTable,
  headlineTable,
  judgeTable,
  levelHeading,
  levelsWithRuns,
  levelTable,
} from './writeup-tables.ts'
import type { RunRecord } from './types.ts'

/** Every run record on disk. */
function loadRecords(): RunRecord[] {
  return readdirSync(RESULTS)
    .filter((f) => f.endsWith('.json') && !f.endsWith('.stream.jsonl'))
    .map((f) => readRecord(readFileSync(join(RESULTS, f), 'utf8')))
}

/** What the set on disk covers, which the prose states before any table is read. */
function coverageOf(records: RunRecord[], casesDefined: number): Coverage {
  const judged = records.filter((r) => r.judgement)
  return {
    runs: records.length,
    valid: records.filter((r) => r.invalid === null).length,
    cases: new Set(records.map((r) => r.caseId)).size,
    casesDefined,
    replicates: records.reduce((most, r) => Math.max(most, r.replicate), 0),
    arms: armsIn(records),
    judgeModel: judged[0]?.judgement?.model ?? null,
    judged: judged.length,
  }
}

/** One comparison: the headline, then a table per difficulty level. */
function comparisonSection(
  comparison: Comparison,
  records: RunRecord[],
  cases: ReturnType<typeof casesById>,
): string {
  // Only the runs of the two arms being compared. A third arm's numbers in this
  // block would be read as part of a pairing it is not in.
  const mine = [
    ...runsOf(records, comparison.reference),
    ...runsOf(records, comparison.contender),
  ]
  const levels = levelsWithRuns(mine, cases).map((group) =>
    sections([
      heading(4, levelHeading(group.level, group.ids)),
      levelTable(group.level, group.ids, mine, comparison),
    ]),
  )
  return sections([
    heading(3, comparison.id),
    `_${questionOf(comparison.kind)}._`,
    headlineTable(mine, comparison),
    ...levels,
  ])
}

/** Every comparison of one kind, under one heading. */
function kindSection(
  title: string,
  note: string,
  comparisons: Comparison[],
  records: RunRecord[],
  cases: ReturnType<typeof casesById>,
): string {
  if (comparisons.length === 0) return ''
  return sections([
    heading(2, title),
    note,
    ...comparisons.map((c) => comparisonSection(c, records, cases)),
  ])
}

/** The document. */
function build(records: RunRecord[]): string {
  const cases = casesById()
  const coverage = coverageOf(records, cases.size)
  const comparisons = comparisonsIn(records)
  const of = (kind: Comparison['kind']): Comparison[] =>
    comparisons.filter((c) => c.kind === kind)

  return `${sections([
    heading(1, 'codedocs fix benchmark — results'),
    '_Generated by `node bench/writeup.ts`. Do not edit by hand._',
    question(),
    provenance(coverage),
    standing(coverage),
    howToRead(),
    kindSection(
      'Like for like',
      `One model, holding the tool and not holding it. This is the claim codedocs
is sold on: the same reasoning capacity, asked the same question, with and
without a structural interface to the repository.`,
      of('like-for-like'),
      records,
      cases,
    ),
    kindSection(
      'A cheaper model holding the tool',
      `Two different models, one on each side. This block asks the second
question — whether structural facts let a cheaper model do work that otherwise
needs a dearer one — and its deltas carry both the toolset's effect and the
models' difference. That is why it is reported apart from the block above and
never averaged with it: pooled together, the two answer neither question.`,
      of('cross-model'),
      records,
      cases,
    ),
    heading(2, 'Discarded runs'),
    `A run is thrown out, never silently counted, when the baseline reached for
codedocs anyway, when the codedocs arm never called it, or when the agent left
no patch at all. Each of those means the comparison would have stopped being
between the two things it claims to compare.`,
    discardedTable(records) || '_No run has been discarded._',
    heading(2, 'The judge'),
    judgeTable(records) || '_No run has been judged._',
    limits(coverage),
    colophon(),
  ])}\n`
}

function main(): void {
  const records = loadRecords()
  if (records.length === 0) {
    console.error('no results yet — run `node bench/run.ts` first')
    process.exitCode = 1
    return
  }
  const document = build(records)
  if (has('stdout')) {
    console.log(document)
    return
  }
  const path = join(BENCH, 'RESULTS.md')
  writeFileSync(path, document, 'utf8')
  console.log(`wrote ${path} from ${records.length} run(s).`)
}

main()
